language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: J38pleZfzHPwYNP+rCgCJi8SudWIYFokg11UK9JB9nywwCrQIfyluX1DBxGNKlA00iI+he0WtN5EBPDTnby2kyJ1TBWXRcrCdOcmud9AU07IynbsMqzqigpK6XNerIQuw/Gf3AHvW4ptVzzcu0ycI3Iuunrxm6yL2L1p8YxVxzzJrUK1dHuap+l1+e+7oiU5+Zdz8keQqGCcsk1mTAHCnMNLDuArZ7lwea+VWltl4Q8LDwVTFxm+KQBbw1xmI8n4AUXu6aDXMDvRo+3RSLOjPSLEAqUapTY1F53U5IzBYez8wugC2x1rDvtcPehLwqk7QqhjSXDmRbdw8VTHEk4g/SDl+TO0VTmf/jfczIc9Hg+7ZRarQM0dbgkVzUYB7wAdzfZ9ceL/LyqzZCMQzJ4LuPzRVWw3gm20wZ4WYE8eIVudmHS0rEALORP23atQJJKTy5rKnwQAku54CQOu77p7DLw2obOd82ZCxW/4rHYRdBHEuohvjPoS7V4BcZ18iSim0aoWRUxJ9P5qq/NuCUOP1uSUu6E27c3sFRghe6e2ju5BTaa5GkyVBEylKXQpB58w+9XfR86+9DXtbzAJGWly/kTsdqpdtyJvmXivF45X5H9Jw35fKYV6LntcPYhfjkonyveKJh4fBYUzwvWNHXYwwMOek56hJDjGvGJO+I6F4TI=
